import "./globals.css";
import { Quicksand } from "next/font/google";
import Header from "@/components/Layout/Header";
import Content from "@/components/Layout/Content";
import Footer from "@/components/Layout/Footer";
import RecoilRoot from "@/recoil/RecoilRoot";
import Providers from "@/components/Layout/Providers";

const quickSand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={quickSand.className}>
      <body className="flex flex-col overflow-auto">
        <RecoilRoot>
          <Providers>
            <Header />
            <Content>{children}</Content>
            <Footer />
          </Providers>
        </RecoilRoot>
      </body>
    </html>
  );
}
