import "./globals.css";
import { Quicksand } from "next/font/google";
import Header from "@/components/Layout/Header";
import Content from "@/components/Layout/Content";
import Footer from "@/components/Layout/Footer";
import RecoilRoot from "@/recoil/RecoilRoot";
import Providers from "@/components/Layout/Providers";

const quickSand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Dante's TechBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={quickSand.className}>
      <body className="flex flex-col overflow-auto mx-auto max-w-3xl lg:max-w-6xl">
        <Providers>
          <RecoilRoot>
            <div className="px-8">
              <Header />
              <Content>{children}</Content>
              <Footer />
            </div>
          </RecoilRoot>
        </Providers>
      </body>
    </html>
  );
}
